### ISSUE TITLE
Can a Logic write to more than one StateRef?

### ISSUE THREAD

**Issue by erf** [letsar/binder#15]
Is there, or should there be, a one-to-one binding between a Logic and a StateRef? Or can a ViewLogic write to several StateRef objects?

**Comment by letsar** [comment]
Yes absolutely. The logic can be the entire business logic of a page or a component and can manage multiple states.

**Comment by erf** [comment]
Ah ok. Great. Maybe something like that could be mentioned in the docs.

**Comment by letsar** [comment]
Yeah I definitely should take more time on the documentation. If you have any idea how to better introduce this package, all ideas are welcome 🙂

**Comment by erf** [comment]
Yes, will do! 

BTW, i've just ported the state solution in my (fairly large) app from RiverPod to Binder :) it went pretty smoothly, and i feel your solution is more sane!

Still some more testing to do, but happy so far! will let you know if i bump into some issues.

**Comment by letsar** [comment]
Wow, that's really great to hear 😊. Do you mind to tell me why you think it's more sane in your opinion, and what would be the advantages and drawbacks of this package versus riverpod?

Knowing this could help people to choose between the two approaches and could also help me to improve this package.

Thanks for your feedback 🙂

**Comment by erf** [comment]
I like that there is less classes / API to deal with.  I don’t have to deal with a many different providers, which makes it easier to make choices and get stuff done. In RiverPod some Providers return AsyncData and some don’t, in Binder the user have to handle loading state himself using either a custom loading state objects or by using Loadable / LogicLoader; for me this makes me more aware of what is going on. There was initially a bit more code to type, but i enjoyed splitting the various state objects into separate files, and when i had done that, i felt i had more control of what was going on, and was able to makes changes more confidently.

**Comment by erf** [comment]
I like that there are less classes and API’s to deal with.  I don’t have to learn many different providers and make choices on what to use, which makes it easier to get stuff done. In RiverPod some Providers return AsyncData and some don’t, in Binder you have to handle loading state yourself using either a loading StateRef or Loadable / LogicLoader; for me this is a cleaner solution. There was initially somewhat more code to type, but i enjoyed splitting the various state objects into separate files, and when finished, i felt more in control of what was going on and was able to makes changes confidently.

**Comment by erf** [comment]
The advantage i see with Riverpod is that you can do more things with less code, and also it is possible to combine async providers.
