### ISSUE TITLE
Uppercase LogicRef when using vscode extension

### ISSUE THREAD

**Issue by chimon2000** [letsar/binder#6]
When using the Logic snippet I noticed that the refs are capitalized. Take the following example.

```
// Should be counterViewLogicRef
final CounterViewLogicRef = LogicRef((scope) => CounterViewLogic(scope));
```

It may be better to have the first tab be for the ref variable and the second to be for the class name.

**Comment by letsar** [comment]
There is something odd with vscode snippets and capitalization. If you type lref, then the prefix of the reference (with camelCase) and then press TAB, the ref should be in camelCase and the name of the class should be rightly capitalized.
Like in this gif:
![lref snippet](https://raw.githubusercontent.com/letsar/flutter-binder-snippets/main/media/lref.gif)

**Comment by chimon2000** [comment]
Ah ok, very odd.  I'll close this one then!
